spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
minio:
  endpoint: "http://192.168.0.105:9001"
  bucket-name: first-image-folder
  access-key: root
  secret-key: 12345678






















